### ISSUE TITLE
API Integration Tracker

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/metascan#146]
### API Integration
- [x] Home Page - Latest transactions @JoshuaC817 
            - https://github.com/WavesHQ/metascan/pull/147
- [x] Home Page - Latest blocks @JoshuaC817 
            - https://github.com/WavesHQ/metascan/pull/147
- [x] Home Page - Search @JoshuaC817 
            - https://github.com/WavesHQ/metascan/pull/149
- [x] Transactions - List @lykalabrada 
            - https://github.com/WavesHQ/metascan/pull/151
- [x] Transactions - Search @JoshuaC817 
            - https://github.com/WavesHQ/metascan/pull/149
- [x] Transaction Details - Data @lykalabrada 
            - https://github.com/WavesHQ/metascan/pull/151
- [x] Blocks - List @pierregee 
            - https://github.com/WavesHQ/metascan/pull/150
- [x] Blocks - Search @JoshuaC817 
            - https://github.com/WavesHQ/metascan/pull/149
- [x] Blocks Details - Data @pierregee 
            - https://github.com/WavesHQ/metascan/pull/150
- [x] Block Details - Transactions @pierregee 
            -  https://github.com/WavesHQ/metascan/pull/169
- [x] Wallet Address - Data @JoshuaC817 
~~- [ ] - Wallet Address - Token Stats~~
- [x] Wallet Address- Transactions List  @JoshuaC817 
~~- [ ] - Wallet Address- Tokens List~~

### Misc Configurations
- [x] Add network change config
       - https://github.com/WavesHQ/metascan/pull/152
- [x] Add security policy headers @JoshuaC817  
       - https://github.com/WavesHQ/metascan/pull/155
       - https://github.com/WavesHQ/metascan/pull/161
- [x] Update content security policy to change eth rpc -> DMC

### API
- [ ] Create RPC for DMC for indexer @pierregee @lykalabrada
