### ISSUE TITLE
feature/contract tracker

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/metascan#172]
### Contracts List Page
- [x] Contracts List with pagination and ui loaders @fullstackninja864  https://github.com/WavesHQ/metascan/pull/202
- [ ] Search by contract https://github.com/BirthdayResearch/metascan/issues/241
- [ ] Verify Contract https://github.com/BirthdayResearch/metascan/issues/240
- [x] Redirect from/to hash on correct page(address/contract) https://github.com/BirthdayResearch/metascan/issues/233

### Contract Detail Page
- [x] Contract Details segment @pierregee https://github.com/BirthdayResearch/metascan/pull/232

**Transactions Tab**
- [x] Transactions List @pierregee https://github.com/BirthdayResearch/metascan/pull/232

**Code Tab**
  - [ ] Add metamask connection https://github.com/BirthdayResearch/metascan/issues/243
  - [ ] Read Contract https://github.com/BirthdayResearch/metascan/issues/237
  - [ ] Write Contract https://github.com/BirthdayResearch/metascan/issues/238
  - [ ] Code Details https://github.com/BirthdayResearch/metascan/issues/239
  - [ ] Read/Write as Proxy (check if feasible first) https://github.com/BirthdayResearch/metascan/issues/242

**Tokens Tab**
- [ ] (?) 
<img width="817" alt="image" src="https://github.com/WavesHQ/metascan/assets/13292662/5ca372da-aa74-4504-9d8d-1272dd41eb4e">
